### ISSUE TITLE
Ouvir evento de ligação

### ISSUE THREAD

**Issue by evertonbzr** [laxeder/rompot#10]
Poderia adicionar para ouvir se recebeu uma ligação dentro do Whatsapp?
Ou instruir a maneria que posso fazer?

**Comment by laxeder** [comment]
Posso adicionar sim, estarei anotando para implementar aqui

**Comment by laxeder** [comment]
Pronto! ([Suporte a chamada](https://github.com/laxeder/rompot/releases/tag/v2.0.9))

*Exemplo:*
```ts
client.on("new-call", async (call) => {
   await call.reject();
   // or
   await client.rejectCall(call);
});
```
